# Generated by Django 5.1.6 on 2025-02-18 03:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_user_bio_remove_user_profile_picture_user_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "modèle de base",
                "verbose_name_plural": "modèles de base",
                "abstract": False,
            },
        ),
    ]
