# Generated by Django 5.1.6 on 2025-02-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'verbose_name': 'Mood', 'verbose_name_plural': 'Moods'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
