# Generated by Django 5.1.6 on 2025-02-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_place_visitedplace_favouriteplace'),
        ('api', '0005_alter_mood_options_alter_user_options'),
    ]

    operations = [
    ]
