# Generated by Django 5.1.6 on 2025-02-20 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_place_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitedplace",
            name="place",
        ),
        migrations.RemoveField(
            model_name="visitedplace",
            name="user",
        ),
        migrations.AddField(
            model_name="visitedplace",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="api.place",
            ),
        ),
        migrations.AddField(
            model_name="visitedplace",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visited_places",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
