# Generated by Django 5.1.6 on 2025-02-20 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_visitedplace_place_remove_visitedplace_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="place",
                to="api.category",
            ),
        ),
    ]
