# Generated by Django 5.1.6 on 2025-02-20 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_moodentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeelingTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("label", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "modèle de base",
                "verbose_name_plural": "modèles de base",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="moodentry",
            name="feelings",
            field=models.ManyToManyField(
                blank=True, related_name="mood_entries", to="api.feelingtag"
            ),
        ),
    ]
