# Generated by Django 5.1.6 on 2025-02-20 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_feelingtag_moodentry_feelings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('slug', models.SlugField(unique=True)),
                ('verbose_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Activity Category',
                'verbose_name_plural': 'Activity Categories',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='Activity Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Estimated Duration (minutes)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/', verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='api.category')),
                ('moods', models.ManyToManyField(related_name='activities', to='api.mood', verbose_name='Moods')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
