version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: moodmap_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    container_name: moodmap_db
    env_file:
      - .envs/.local/.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
