name: Backend Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Poetry via pip
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        cd backend  # Navigate to the backend directory
        poetry install --no-root  # Install dependencies without installing the package

    - name: Run tests with pytest
      env:
        PYTHONPATH: ${{ github.workspace }}/backend  # Add backend to Python path
        DJANGO_SETTINGS_MODULE: config.settings  # Replace with your actual settings module
      run: |
        cd backend  # Navigate to the backend directory
        poetry run pytest  # Run pytest with Poetry